add restart,reload,status,sleep,awake,default,daemon,help flags

diff --git a/simple-power-manager b/simple-power-manager
--- a/simple-power-manager
+++ b/simple-power-manager
@@ -22,93 +22,207 @@
 #    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 #    SOFTWARE.
 
-# Dependencies:
-# The "acpi" command is used to determine the current battery level
-# The "notify-send" command (libnotify) is used to send desktop notifications
-# The user_custom functions are configured for xbacklight/acpilight already-- users of lux, light or whatever will need to customize
+die() {
+    [ $# -gt 0 ] && printf -- "%s\n" "$(tput setaf 1)$*"
+    exit 1
+}
 
-while true; do
-    ############################################################################
-    # battery polling frequency
-    sleep 5
+help() {
+    cat << EOF
+Usage: simple-power-manager [OPTION...]
 
-    # if trigger has not already been fired, and if battery % is less than or equal
-    # to a threshold and if battery state is Discharging, then run user_custom_low_battery_hook
-    user_custom_low_battery_hook() {
-        if [ "$batt" -lt 100 ] && [ "$batt" -gt 80 ]; then
-            # 80-99% battery
-            echo # do nothing
+  -d, --daemon               start the daemon and fork the process
+  -D, --default              regenerates the default configuration file to $HOME/.config/simple-power-manager/config
+  --reload                   reload the configuration file
+  --restart                  wipe simple-power-manager temporary state (from /tmp) and restart the daemon
+  --sleep                    put the daemon in a sleep loop
+  --awake                    awake the daemon from a sleep loop
+  --status                   display whether the state is running (awake) or paused (asleep)
+  -h, --help                 display this help menu
+EOF
+    exit 0
+}
 
-        elif [ "$batt" -lt 81 ] && [ "$batt" -gt 40 ]; then
-            # 40-80% battery
-            echo # do nothing
-
-        elif [ "$batt" -lt 41 ] && [ "$batt" -gt 20 ]; then
-            # 20-40% battery
-            echo # do nothing
-
-        elif [ "$batt" -lt 21 ] && [ "$batt" -gt 10 ]; then
-            # 10-20% battery
-            notify-send "Battery: $batt"
-            xbacklight -set 20
-
-        elif [ "$batt" -lt 11 ] && [ "$batt" -gt 5 ]; then
-            # 5-10% battery
-            notify-send "Battery: $batt"
-            xbacklight -set 10
-
-        elif [ "$batt" -lt 6 ]; then
-            # 5% battery or less
-            notify-send "Battery: $batt"
-            xbacklight -set 5
-        fi
-    }
-
-    # if trigger has not already been fired, and if battery state is Charging or
-    # Full, then run user_custom_battery_normal_hook
-    user_custom_battery_normal_hook() {
-        # battery Charging / Full
-        notify-send "Battery: $acpi_status $batt"
-        xbacklight -set 80
-    }
-    ############################################################################
-
-    bail() {
-        [ $# -gt 0 ] && printf -- "%s\n" "$*"
-        break
-    }
-    if [ ! -d /tmp/battmon ];then
-        command -v acpi > /dev/null || bail "acpi not found"
-        mkdir /tmp/battmon || bail "/tmp is not writeable"
-    fi
+acpi_info() {
     acpi="$(acpi | awk '{print $3 $4}')"
     batt="${acpi#*,}" ; batt="${batt%\%*}"
     acpi_status="${acpi%%,*}"
-    intcheck () {
-        case ${1#[-+]} in
-            *[!0-9]* | '') return 1 ;;
-            * ) return 0 ;;
-        esac
-    }
-    intcheck "$batt" || bail "$batt is not an integer"
-    if [ "$acpi_status" = "Discharging" ];then
-        batt_thresholds="99 80 40 20 10 5"
-        echo "$batt_thresholds" | tr ' ' '\n' | while read -r thresh; do
-            if [ "$batt" -eq "$thresh" ] || [ "$batt" -lt "$thresh" ]; then
-                if [ ! -f "/tmp/battmon/$thresh" ]; then
-                    if [ -f "/tmp/battmon/100" ]; then rm /tmp/battmon/100; fi
-                    touch "/tmp/battmon/$thresh"
-                    user_custom_low_battery_hook
+}
+
+daemon_start() {
+    while true; do
+        # if daemon is locked, enter a sleep loop
+        until [ ! -f /tmp/simple-power-manager/state/lock ]; do sleep 1; done
+
+        # one-time setup
+        if [ ! -d /tmp/simple-power-manager ];then
+            # verify acpi is available and create dir structure in /tmp
+            command -v acpi > /dev/null || die "acpi not found"
+            mkdir -p /tmp/simple-power-manager/state || die "/tmp is not writeable"
+
+            # create default user local dir structure
+            [ ! -d "$HOME/.config/simple-power-manager" ] && mkdir -p "$HOME/.config/simple-power-manager"
+            [ ! -f "$HOME/.config/simple-power-manager/config" ] &&  make_defconfig
+        fi
+
+        # sourcing of the user config file happens now
+        if [ -f "/tmp/simple-power-manager/config" ];then
+            . "/tmp/simple-power-manager/config"
+        else
+            daemon_reload
+            . "/tmp/simple-power-manager/config"
+        fi
+
+        # get battery % and status
+        acpi_info
+
+        # discharge loop
+        if [ "$acpi_status" = "Discharging" ];then
+            batt_thresholds="99 80 40 20 10 5"
+            echo "$batt_thresholds" | tr ' ' '\n' | while read -r state; do
+                if [ "$batt" -eq "$state" ] || [ "$batt" -lt "$state" ]; then
+                    if [ ! -f "/tmp/simple-power-manager/state/$state" ]; then
+                        if [ -f "/tmp/simple-power-manager/state/100" ]; then rm /tmp/simple-power-manager/state/100; fi
+                        touch "/tmp/simple-power-manager/state/$state"
+                        user_custom_low_battery_hook
+                    fi
                 fi
+            done
+        fi
+
+        # charge / full loop
+        if [ "$acpi_status" = "Charging" ] || [ "$acpi_status" = "Full" ]
+        then
+            if [ ! -f "/tmp/simple-power-manager/state/100" ];then
+                echo "$batt_thresholds" | tr ' ' '\n' | while read -r state; do
+                    [ -f "/tmp/simple-power-manager/state/$state" ]&&  rm "/tmp/simple-power-manager/state/$state"
+                done
+                touch /tmp/simple-power-manager/state/100
+                user_custom_battery_normal_hook
             fi
-        done
+        fi
+    done & # fork the process
+}
+
+make_defconfig() {
+    if [ ! -f "$HOME/.config/simple-power-manager/config" ];then
+        cat <<EOF > "$HOME/.config/simple-power-manager/config"
+#################################################################################
+# simple-power-manager configuration - /bin/sh - it's shell script, be careful! #
+#################################################################################
+
+# battery polling frequency
+sleep 5
+
+# if trigger has not already been fired, and if battery % is less than or equal
+# to a threshold and if battery state is Discharging, then run user_custom_low_battery_hook
+user_custom_low_battery_hook() {
+    if [ "\$batt" -lt 100 ] && [ "\$batt" -gt 80 ]; then
+        # 80-99% battery
+        echo # do nothing
+
+     elif [ "\$batt" -lt 81 ] && [ "\$batt" -gt 40 ]; then
+        # 40-80% battery
+        echo # do nothing
+
+     elif [ "\$batt" -lt 41 ] && [ "\$batt" -gt 20 ]; then
+        # 20-40% battery
+        echo # do nothing
+
+     elif [ "\$batt" -lt 21 ] && [ "\$batt" -gt 10 ]; then
+        # 10-20% battery
+        notify-send "Battery: \$batt"
+        xbacklight -set 20
+
+     elif [ "\$batt" -lt 11 ] && [ "\$batt" -gt 5 ]; then
+        # 5-10% battery
+        notify-send "Battery: \$batt"
+        xbacklight -set 10
+
+     elif [ "\$batt" -lt 6 ]; then
+        # 5% battery or less
+        notify-send "Battery: \$batt"
+        xbacklight -set 5
     fi
-    if [ "$acpi_status" = "Charging" ] || [ "$acpi_status" = "Full" ]
-    then
-        if [ ! -f "/tmp/battmon/100" ];then
-            rm /tmp/battmon/*
-            user_custom_battery_normal_hook
-            touch /tmp/battmon/100
+}
+
+# if trigger has not already been fired, and if battery state is Charging or
+# Full, then run user_custom_battery_normal_hook
+user_custom_battery_normal_hook() {
+    # battery Charging / Full
+    notify-send "Battery: \$acpi_status \$batt"
+    xbacklight -set 80
+}
+EOF
+        echo "Configuration script written to $HOME/.config/simple-power-manager/config"
+        echo "Please modify it accordingly before running simple-power-manager again."
+    else
+        die "Configuration script already exists in $HOME/.config/simple-power-manager/config"
+    fi
+}
+
+daemon_restart() {
+    restart() {
+        echo "Cleaning /tmp/simple-power-manager"
+        rm -rf /tmp/simple-power-manager
+        echo "Restarting Daemon"
+        ~/repos/simple-power-manager/simple-power-manager -d
+    }
+    trap restart INT TERM
+    killall simple-power-ma
+}
+
+daemon_reload() {
+    cp "$HOME/.config/simple-power-manager/config" /tmp/simple-power-manager/config && \
+        echo "User configuration loaded."
+}
+
+daemon_sleep() {
+    touch /tmp/simple-power-manager/state/lock && \
+        echo "Simple Power Manager daemon is sleeping."
+}
+
+daemon_awake() {
+    rm /tmp/simple-power-manager/state/lock && \
+        echo "Simple Power Manager daemon is running."
+}
+
+daemon_status() {
+    acpi_info ; echo "Battery: $acpi_status $batt"
+
+    spmcount="$(pgrep simple-power-ma | wc -l)"
+
+    if [ "$spmcount" -gt 3 ]; then
+        pgrep -a simple-power-ma
+        die "WARNING: There is more than one instance of simple-power-manager running! (Try 'simple-power-manager --restart')"
+    elif [ "$spmcount" -lt 3 ]; then
+        die "Simple Power Manager is not running."
+    fi
+
+    if [ ! -f /tmp/simple-power-manager/state/lock ]; then
+        if [ "$spmcount" -eq 3 ]; then
+            echo "Simple Power Manager daemon is running."
+        fi
+    else
+        if [ "$spmcount" -eq 3 ]; then
+            echo "Simple Power Manager daemon is sleeping."
         fi
     fi
-done
+}
+
+[ $# -lt 1 ] && help && return 1
+[ $# -gt 1 ] && help && return 1
+case $1 in
+    -d        ) daemon_start ;;
+    --daemon  ) daemon_start ;;
+    -D        ) make_defconfig ;;
+    --default ) make_defconfig ;;
+    --reload  ) daemon_reload ;;
+    --sleep   ) daemon_sleep ;;
+    --awake   ) daemon_awake ;;
+    --status  ) daemon_status ;;
+    --restart ) daemon_restart ;;
+    -h        ) help ;;
+    --help    ) help ;;
+    *         ) help; return 1 ;;
+esac
